# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EbizOffice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EbizOffice
  pod 'Firebase'
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'Firebase/Core', '~> 5.3.0'
  
  target 'EbizOffice-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  end

  target 'EbizOfficeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EbizOffice-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EbizOffice-tvOS

  # target 'EbizOffice-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
