# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VanBanDOJI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VanBanDOJI
  pod 'Firebase/Messaging'
  target 'VanBanDOJI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

    # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'RNReactNativeDocViewer', :path => '../node_modules/react-native-doc-viewer'


    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'VanBanDOJITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'VanBanDOJI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VanBanDOJI-tvOS

  # target 'VanBanDOJI-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
