export const UPDATE_CORE_NAV_PARAMS = 'UPDATE_CORE_NAV_PARAMS';
export const UPDATE_EXTENDS_NAV_PARAMS = 'UPDATE_EXTENDS_PARAMS';

export const UPDATE_PAST_CORE_NAV_PARAMS = 'SAVE_PAST_CORE_NAV_PARAMS';
export const UPDATE_ACTION_ID = 'UPDATE_ACTION_ID';